# Generated by Django 4.0 on 2021-12-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_usermodel_privet_usermodel_image_field_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
