# Generated by Django 4.0 on 2021-12-16 18:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0003_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privateKey', models.CharField(blank=True, max_length=100)),
                ('publicKey', models.CharField(blank=True, max_length=100)),
                ('masterpassword', models.CharField(blank=True, max_length=100)),
                ('image_field', models.ImageField(null=True, upload_to='')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
            ],
        ),
    ]
